services:
  # ---- Backend (Spring Boot)  ----
  - type: web
    name: tfg-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: NODE_ENV
        value: production
      - key: EMAIL_PROVIDER
        value: brevo
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USER
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_FROM_EMAIL
        sync: false
      - key: EMAIL_FROM_NAME
        value: Polan
      - key: APP_FRONTEND_BASE_URL
        sync: false
