sonar.projectKey=Mancalrod_TFG_backend
sonar.organization=mancalrod
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.sourceEncoding=UTF-8
